### ISSUE TITLE
Run MiniMesos in a container

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#107]
Currently MiniMesos runs as java -jar and this requires Java 8. Additionally this setup is difficult for Docker Machine / Mac Os X users since the MiniMesos process runs on the host while its containers run in Docker Machine which makes communication between these processes difficult.

- [x] Add a minimesos image which contains a Zulu OpenJDK 8 build and the minimesos Jar
- [x] Configure the minimesos image build in gradle 
- [x] Change the minimesos script so it runs docker run minimesos and mount the Docker socket as a volume

**Comment by sadovnikov** [comment]
@frankscholten , is it necessary to use Zulu Open JDK? Does ```apt-get install openjdk-8-jre-headless``` violate something?

**Comment by sadovnikov** [comment]
Still to implement
- [ ] push minimesos image to Docker Hub on release of minimesos
- [ ] add image versioning to ```minimesos``` script
- [ ] minimise size of minimesos image
