### ISSUE TITLE
using minimesos for unit testing of framework

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#114]
create an example of a simplest framework, which uses minimesos for unit testing.
This example should be used in system test of minimesos and also included to documentation

**Comment by alex-glv** [comment]
+1

**Comment by frankscholten** [comment]
I am currently implementing this as part of the [minimesos install command](https://github.com/ContainerSolutions/minimesos/issues/93) and merging the  https://github.com/ContainerSolutions/mesos-hello-world inside minimesos so it will be tested.

**Comment by frankscholten** [comment]
The hello world framework still uses Docker and will take some refactoring to use it with jars. Will add it later.

I will have the test depend on Elasticsearch on Jitpack.

**Comment by sadovnikov** [comment]
adjusting https://github.com/ContainerSolutions/mesos-hello-world to work with ``minimesos:0.4.0``

**Comment by sadovnikov** [comment]
https://github.com/ContainerSolutions/mesos-hello-world will be copied to ``minimesos`` project and used in its tests

**Comment by frankscholten** [comment]
Merged https://github.com/ContainerSolutions/minimesos/pull/150
