### ISSUE TITLE
Use consistent spelling of minimesos

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#115]
We use different spellings for minimesos. Let's use ``minimesos`` as the default spelling and update code, docs and GH repo.

**Comment by frankscholten** [comment]
- [x] Twitter account
- [ ] Code
- [ ] Website

**Comment by frankscholten** [comment]
Because the repo has been updated the website gives a 404. Contacted Github about this.

**Comment by jrslv** [comment]
Also the URL in blog posts should be updated

**Comment by frankscholten** [comment]
Website is back! http://minimesos.org

It will be rebuild when you push the branch
