### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by ZeissS** [ContainerSolutions/minimesos#126]
If you install minimesos as described on the website, it won't install the .jar anymore and thus every invocation just prints an error that the jar is missing.

I tracked this down to this commit: https://github.com/ContainerSolutions/minimesos/commit/3ee8ba046121bdfc238e43ffa7b36304ddcdfcfb#diff-81fd2adb13518cfcf88c004b912c4d9fL20

Not sure what was done there, but we either need to fix the website to document the new installation process of this the installation script.

**Comment by frankscholten** [comment]
Thanks for reporting @ZeissS!

Let's fix the installation script. Do you want to add a PR?

**Comment by frankscholten** [comment]
Turns out ``containersol/minimesos:latest`` was not pushed. Pushed it and simplified install script.
