### ISSUE TITLE
There is a busybox container left over after running tests

### ISSUE THREAD

**Issue by remmelt** [ContainerSolutions/minimesos#129]
Command: `/bin/sh -c 'echo 1'`

Should be removed after use.

**Comment by sadovnikov** [comment]
``containersol/minimesos:latest`` is also left. Should be deleted too

**Comment by remmelt** [comment]
For that last bit, see https://github.com/ContainerSolutions/minimesos/pull/128 and https://github.com/ContainerSolutions/minimesos/issues/124

**Comment by sadovnikov** [comment]
![screen shot 2015-10-26 at 14 31 32](https://cloud.githubusercontent.com/assets/4749332/10730140/6b3b51e8-7bee-11e5-9a08-0c02f9576db1.png)
