### ISSUE TITLE
Installation is still broken

### ISSUE THREAD

**Issue by ZeissS** [ContainerSolutions/minimesos#131]
Since I can't reopen #126, here I am again. I wiped my local state, went to minimesos.org and copied the command again. I didn't do the `sudo` thing, but on my Mac OS with Homebrew that doesn't seem to be necessary. Again, the outcome is that the jar file is not available.

```
Kallisto:releaseit zeisss$ sudo rm -rf /usr/local/bin/minimesos /usr/local/share/minimesos/
Password:
Kallisto:releaseit zeisss$ curl https://raw.githubusercontent.com/ContainerSolutions/minimesos/master/bin/install | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1069  100  1069    0     0   1297      0 --:--:-- --:--:-- --:--:--  1295
Installing minimesos 0.4.0
Done
Kallisto:releaseit zeisss$ minimesos
Error: Unable to access jarfile /usr/local/share/minimesos/mini-mesos.jar
Kallisto:releaseit zeisss$ cat /usr/local/bin/minimesos
#!/bin/sh

java -jar /usr/local/share/minimesos/mini-mesos.jar $@
```

**Comment by sadovnikov** [comment]
The root cause is that the installation script is taken from the master branch, however it installs the latest released version of the script. Therefore there is a mismatch... 
... figuring out how separate two install scripts
