### ISSUE TITLE
Refactor configuration object out into CLI configuration object, like ES

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/minimesos#148]
The ClusterConfig object has state and is not really a cluster config. It should be a CLI config, like ES uses. That would instantly make all configuration options user selectable and make the configuration object more immutable and decoupled from Mesos specific state.

Oh, it's nearly done already! Will finish off the task.

**Comment by frankscholten** [comment]
Already implemented in ClusterArchitecture
