### ISSUE TITLE
clean termination of minimesos

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#149]
``minimesos`` should terminate all running tasks upon exiting. This will eliminate the need to stop executor containers

**Comment by sadovnikov** [comment]
- use reverse order for stopping cluster containers;
- invoke graceful stop on containers, which do not compose Mesos cluster - stop schedulers;
- give schedulers sometime to stop;
- use agents and master to clean up remaining tasks and frameworks;
- remove cluster containers;

![image](https://cloud.githubusercontent.com/assets/4749332/13280833/948750b4-dae0-11e5-87a2-b1eeaabf3e25.png)

**Comment by mwl** [comment]
Well, that drawing explains everything

**Comment by JamieDobsonCS** [comment]
Martin....

**Comment by frankscholten** [comment]
@sadovnikov Is this one still relevant?

**Comment by frankscholten** [comment]
This one is fixed after refactoring of `MesosCluster.destroy` method.
