### ISSUE TITLE
Add "minimesos state" command

### ISSUE THREAD

**Issue by jrslv** [ContainerSolutions/minimesos#151]
Add `mesos state [--agent <agent-id>]` CLI command that prints out state of either the master or slave in JSON representation.

**Comment by frankscholten** [comment]
Correction: the command is ``minimesos state`` and should print state of the entire cluster.

**Comment by jrslv** [comment]
@frankscholten Why would you always display all at once?

**Comment by frankscholten** [comment]
because the ``state.json`` file contains all the information of the cluster. The ``state`` command should show the same information and is ``jq``-able by the user.

**Comment by jrslv** [comment]
You can do `curl http://<master>/state.json` and `curl http://<slave>/state.json` and get distinct information.

**Comment by frankscholten** [comment]
Yes. Then ``state`` should use the master by default and also allow slave parameter

**Comment by jrslv** [comment]
Yes. That's what the original approach describes. And it also counts for the fact there could be more slaves, errr agents to use the proper naming convention;)

**Comment by sadovnikov** [comment]
@jrslv 's PR is merged.... after serious merging. Thanks
