### ISSUE TITLE
single location for mesos container base

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#155]
we have a few places, where base for mesos containers is set. Ideally, there should be only one

![screen shot 2015-11-10 at 13 17 22](https://cloud.githubusercontent.com/assets/4749332/11062250/a507943e-87ad-11e5-85cc-e550284e624c.png)

**Comment by frankscholten** [comment]
@sadovnikov Is this one still relevant after 0.6.1 refactoring and config file code?
