### ISSUE TITLE
Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/minimesos#164]
minimesos fails to start
```
$ minimesos up --exposedHostPorts
Pulling images required to launch minimesos ...
Finished pulling images.
Container [minimesos-agent-207710836-4094612196] did not start within 60 seconds.
```
logs how a problem with detecting docker version
```
$ docker logs minimesos-agent-207710836-4094612196
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1112 13:50:08.837334  9230 process.cpp:995] libprocess is initialized on 172.17.0.5:5051 for 8 cpus
I1112 13:50:08.837586  9230 logging.cpp:172] INFO level logging started!
I1112 13:50:08.837796  9230 logging.cpp:177] Logging to /var/log
I1112 13:50:08.837823  9230 main.cpp:185] Build: 2015-10-12 20:57:28 by root
I1112 13:50:08.837841  9230 main.cpp:187] Version: 0.25.0
I1112 13:50:08.837891  9230 main.cpp:190] Git tag: 0.25.0
I1112 13:50:08.837908  9230 main.cpp:194] Git SHA: 2dd7f7ee115fe00b8e098b0a10762a4fa8f4600f
Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to get docker version: Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127
```
Environment
```
$ cat /etc/issue
Ubuntu 15.04 \n \l
$ uname -a
Linux ubuntu-VirtualBox 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
tried both with docker
* Docker version 1.8.3, build f4bf5c7
* Docker version 1.9.0, build 76d6bc9

**Comment by sjoerdmulder** [comment]
I have the same issue with Ubuntu 14.04 and Docker 1.9.0

**Comment by mdirkse** [comment]
How did you install your docker binaries? I had the same problem and it took a little digging to get the actual, underlying error. Here's how.

First, start a bash shell in the minimesos agent container and mount the docker binary:
```shell
docker run -ti --entrypoint=/bin/bash -v /usr/bin/docker:/usr/bin/docker containersol/mesos-agent:0.25.0-0.2.70.ubuntu1404
```

Then run the `docker` command, and you'll probably see
```
docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
```

The problem here is that the docker binary is *dynamically linked*. This didn't used to be the case, it only happened when Docker [moved to the new binary repositories](https://blog.docker.com/2015/07/new-apt-and-yum-repos/). Not sure why they did it, but they did. Before that all docker binaries were statically linked and things like `libapparmor.so.1` were baked into the executable. This is no longer the case, which means that, if you mount your binary from your host system into your container, and that container doesn't contain the necessary dynamic libraries (and the minimesos agent image does not) , things won't work.

The most practical workaround I could come up with was to replace the `/usr/bin/docker` provided by the docker package (the dynamically linked version) with the good ol' statically linked binary, which is still available (for 1.9.0, for instance, you can get it here https://get.docker.com/builds/Linux/x86_64/docker-1.9.0). Once you've done that everything should work again.

@frankscholten perhaps the minimesos documentation should specify that you need a statically linked Docker binary. Either that, or minimesos should not mount the docker binary into the container but just use the one that's already in there. Of course this may cause compatibility issues between the client and the host daemon if there versions differ too much.

**Comment by frankscholten** [comment]
@mdirkse Great detective work, thanks! @sadovnikov just added this one to the 0.5.0 milestone

**Comment by sadovnikov** [comment]
I'm not sure how we can resolve this within `minimesos` 

```
vagrant@vagrant:/host/sources/mini-mesos$ ldd `which docker`
	linux-vdso.so.1 =>  (0x00007fff6affe000)
	libapparmor.so.1 => /usr/lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007f801387f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8013661000)
	libdevmapper.so.1.02.1 => /lib/x86_64-linux-gnu/libdevmapper.so.1.02.1 (0x00007f8013427000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8013061000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8013a93000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f8012e3e000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f8012c2c000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f80129ee000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f80127ea000)
	libcgmanager.so.0 => /lib/x86_64-linux-gnu/libcgmanager.so.0 (0x00007f80125cf000)
	libnih.so.1 => /lib/x86_64-linux-gnu/libnih.so.1 (0x00007f80123b7000)
	libnih-dbus.so.1 => /lib/x86_64-linux-gnu/libnih-dbus.so.1 (0x00007f80121ad000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f8011f67000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8011d5f000)
```

unless we revert back to docker-in-docker setup...

**Comment by sadovnikov** [comment]
from https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

> Some adventurous folks have tried to bind-mount /var/lib/docker from the host into the Docker-in-Docker container. Sometimes they share /var/lib/docker with multiple containers. 
> The Docker daemon was explicitly designed to have exclusive access to /var/lib/docker. Nothing else should touch, poke, or tickle any of the Docker files hidden there.

However in `The solution` section he still recommends 

```
docker run -v /var/run/docker.sock:/var/run/docker.sock \
           -v $(which docker):/bin/docker \
           -ti ubuntu
```

**Comment by sadovnikov** [comment]
I tried "the solution" - not working

```
vagrant@vagrant:/host/sources/mini-mesos$ docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/bin/docker -ti ubuntu
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
Digest: sha256:f91f9bab1fe6d0db0bfecc751d127a29d36e85483b1c68e69a246cf1df9b4251
Status: Downloaded newer image for ubuntu:latest
root@5c397cd00fb6:/# docker ps
docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
```

**Comment by mdirkse** [comment]
Did you download the static binary?

**Comment by sadovnikov** [comment]
No, I did not, as this library has to be replaced on hosts. By "the solution" I referred to a paragraph on https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/

**Comment by mdirkse** [comment]
Ah right, sorry.

**Comment by sadovnikov** [comment]
Suggestion of @mdirkse seems to be working. I created a container with docker. After that executed `docker run -v /var/run/docker.sock:/var/run/docker.sock -ti sadovnikov/containers` and then `docker run -ti ubuntu:14.04` within that container. After that both containers are visible on host

```
vagrant@vagrant:~$ docker ps
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS              PORTS               NAMES
b64918154693        ubuntu:14.04            "/bin/bash"         12 seconds ago      Up 11 seconds                           thirsty_archimedes
7aee2d026111        sadovnikov/containers   "/bin/bash"         2 minutes ago       Up 2 minutes                            fervent_poitras
``` 

The question is: what version of docker we should install in `minimesos` containers, so it can work with 1.7, 1.8 and 1.9 docker on hosts?

**Comment by mdirkse** [comment]
Is there some sort of compatibility issue between the versions? I'd go for 1.9, and if we really need another version perhaps bake in 1.8 as well, and allow users to switch between the two with a command line flag or something

**Comment by sadovnikov** [comment]
We need to decide (and state in documentation) the docker versions we support. Take https://docs.docker.com/engine/reference/api/docker_remote_api/ into account

**Comment by sadovnikov** [comment]
@frankscholten, @lguminski, seems I managed to resolve this but in `bug\164` branch. 
* docker 1.7.1 is added to `minimesos` container
* almost all volume mappings in `minimesos` script to start container and in `minimesos` container to start mesos slaves containers are removed. Mapping of `docker.sock` is the only one, which is kept in both cases

This is enough to let 1.7.1 docker "client" to use docker on host to pull images and to start containers. Tested on MAC OS X with docker-machine 1.9.1 and on `ubuntu-14.04` with docker 1.9.1. 

Will appreciate if you can try this version too

**Comment by sadovnikov** [comment]
Will also appreciate any recommendations fro speeding up buildi of https://github.com/ContainerSolutions/minimesos/blob/bug/164/minimesos/Dockerfile container and code changes in PR #172

**Comment by mdirkse** [comment]
@sadovnikov re de Dockerfile recommendations, see PR #174

**Comment by sadovnikov** [comment]
I'd like to confirm, there are problems with minimesos build on machines with docker 1.7.1

**Comment by sadovnikov** [comment]
The problem was resolved in master branch

**Comment by sadovnikov** [comment]
and after all these
```
Failed to start minimesos-zookeeper-582694213-607032657 () container
com.github.dockerjava.api.BadRequestException: client version 1.7.1 is too old. Minimum supported API version is 1.21, please upgrade your client to a newer version
```
