### ISSUE TITLE
Use Mesosphere docker images for Mesos master and agent instead of ContainerSolutions ones

### ISSUE THREAD

**Issue by mdirkse** [ContainerSolutions/minimesos#166]
Why is it that minimesos uses ContainerSolutions Docker images for Mesos instead of the regular ones from Mesosphere?

I think it'd be better to use the official Mesosphere ones, not least because this would save ContainerSolutions from having to bake and publish images every time Mesosphere does an update.

**Comment by frankscholten** [comment]
We use our own ones to support Java 8. See https://github.com/ContainerSolutions/minimesos/issues/106

**Comment by sadovnikov** [comment]
@frankscholten has explained it
