### ISSUE TITLE
Publish ZooKeeper port

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/minimesos#176]
`--exposedHostPorts` options should expose also 2181 from ZooKeeper

**Comment by frankscholten** [comment]
This could lead to problems when we support a Zookeeper ensemble consisting of several Zookeeper instances. https://github.com/ContainerSolutions/minimesos/issues/16

**Comment by frankscholten** [comment]
We decided we will support publishing the Zookeeper port to the host
