### ISSUE TITLE
reduce size of minimesos image

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#178]
this has been started by #174, however not merged fully
* installation of docker to downloading the binary is implemented
* based on https://github.com/docker-library/official-images/issues/625#issuecomment-87734364 we'll stay on Open JDK
* basing image on `alpine:3.2` is to be implemented

Suggested by @mdirkse Dockerfile is attached 
[Dockerfile.txt](https://github.com/ContainerSolutions/minimesos/files/49496/Dockerfile.txt)

**Comment by frankscholten** [comment]
Closing because I tried out the snippet from #286 but it ends up as being larger then the current one. 

```frank@franktop:~/src/minimesos$ docker images | grep minimesos
containersol/minimesos                     latest                        3560e4fc2c5b        29 seconds ago      272.1 MB
containersol/minimesos                     0.7.1                         55d069def055        8 days ago          130.6 MB
```
