### ISSUE TITLE
Gradle install produces invalid jar file on jitpack

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/minimesos#181]
On version 0.5.0, jitpack (and presumerably the gradle install command) does not correctly package the minimesos jar.

To reproduce:
Download the built jar from jitpack: https://jitpack.io/com/github/ContainerSolutions/mini-mesos/0.5.0/mini-mesos-0.5.0.jar
Rename to a zip. Extract the files. See that there are no minimesos files in there.

Jitpack build log, for reference:
https://jitpack.io/com/github/ContainerSolutions/mini-mesos/0.5.0/build.log

Comparing 0.5.0 contents, compared to old, working version, for reference:
```
[phil-mac@Phils-MacBook-Pro Downloads ]$ ls -l mini-mesos-0.5.0
total 0
drwxr-xr-x@ 5 phil-mac  staff  170  8 Dec 13:34 META-INF
drwxr-xr-x@ 4 phil-mac  staff  136  8 Dec 13:34 javax
[phil-mac@Phils-MacBook-Pro Downloads ]$ ls -l mini-mesos-9d8c635265
total 8
drwxr-xr-x@ 3 phil-mac  staff  102 13 Nov 09:52 META-INF
drwxr-xr-x@ 3 phil-mac  staff  102 13 Nov 09:52 com
-rw-r--r--@ 1 phil-mac  staff  412 13 Nov 09:52 logback.xml
```
Only code in 0.5.0 is javax. Code is present in old version.

**Comment by philwinder** [comment]
Looking at the build log, it seems that the first correct minimesos build is then cleaned, and overwritten by a second build of some tests.

**Comment by sadovnikov** [comment]
Although the issue remains valid, the URL should be https://jitpack.io/com/github/ContainerSolutions/minimesos/0.5.0/minimesos-0.5.0.jar.

The build log is https://jitpack.io/com/github/containersolutions/minimesos/0.5.0/build.log

**Comment by sadovnikov** [comment]
![image](https://cloud.githubusercontent.com/assets/4749332/11657572/ed627bce-9dbd-11e5-97e9-7f5094b29285.png)

**Comment by mwl** [comment]
First of all, I want to see the whole build output. That's why I was asking for the directory listing access. They have acknowledged the issue and are looking into it right now.

**Comment by sadovnikov** [comment]
@mwl, thanks a lot

**Comment by philwinder** [comment]
Ok, I've found the breaking commit.
This commit works, 9d8c635265e6932b9c6769192f2f4df18f0328c7
And the next commit, it doesn't.
183f6f6647ed5c8702741527954f12066e476ef0

**Comment by philwinder** [comment]
FYI @mwl, you can see the generated files in the logs. You don't strictly need directory listing access.

**Comment by sadovnikov** [comment]
I got https://jitpack.io/com/github/ContainerSolutions/minimesos/356260f/minimesos-356260f.jar from JitPack. This commit is after the refactoring (just 2 commits before the release) and it CONTAINS minimesos classes. I believe things got mixed up by accidental pulling of mini-mesos. Now jars are cached in JitPack

**Comment by mwl** [comment]
Jitpack guys just came back to me
> found the issue. there were some extra artifacts generated in build/tmp which were confugins JitPack. fixed that and rebuilt 0.5.0

**Comment by sadovnikov** [comment]
However the content of 0.5.0 is still wrong
> Hi, thank you for helping out. However we still have a problem. The content of https://jitpack.io/com/github/ContainerSolutions/minimesos/0.5.0/minimesos-0.5.0.jar is still wrong. Seems it got mixed up by building from renamed "mini-mesos" repository instead of "minimesos". However the content of https://jitpack.io/com/github/ContainerSolutions/minimesos/356260f/minimesos-356260f.jar (two very small commits before the release) is valid. Is it possible to remove minimesos-0.5.0.jar from JitPack and to rebuild it?

**Comment by sadovnikov** [comment]
![image](https://cloud.githubusercontent.com/assets/4749332/11659127/e56cf422-9dc6-11e5-88bd-b22abb653ddf.png)

**Comment by sadovnikov** [comment]
To prevent this mess from happening in future, the one, who makes the release, should get download the JAR from JitPack as soon as tag is created... pardon me, did not know this
