### ISSUE TITLE
duplication when it comes to the MarathonClient

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#184]
When we are in “destroy” and “install” commands, we don’t really have a proper `MesosCluster`. 
We are not able to restore `AbstractContainer` objects from actually running cluster….  we’d need `MesosCluster(String clusterId)` constructor, which loops through running docker containers and restores objects to represent them. And then get rid of static methods in `MesosCluster`

**Comment by frankscholten** [comment]
+1

**Comment by frankscholten** [comment]
Duplicate of https://github.com/ContainerSolutions/minimesos/issues/213
