### ISSUE TITLE
minimesos configuration file

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#185]
More and more options are being added to `minimesos` CLI. While this approach is valid, it will be convenient to have cluster configuration file in the current directory and to let CLI parameters to overwrite it. The similar approach is used by [Vagrant](https://www.vagrantup.com/)

The configuration should include:
* number of agents and their resources
* ..

Please, comment with your ideas here

**Comment by frankscholten** [comment]
Yes, this is a great feature. 

Here is a link to the [http://mesos.apache.org/documentation/latest/configuration/|Mesos configuration]. Let's start with cluster level configuration 

- [ ] Number of agents
- [ ] Mesos version
- [ ] Log level
- [ ] Cluster name

**Comment by mdirkse** [comment]
Agreed! Perhaps with something like a `minimesos init` that outputs a config file with the defaults?

My suggestions for inclusion in the file:
- ability to specify version for any image
- Optionally specify other, arbitrary images to start along with the cluster (a consul image for instance)
- ability to specify (within reason) IP's or different networking options

**Comment by frankscholten** [comment]
@mdirkse Sounds great!

**Comment by frankscholten** [comment]
First draft of configuration file

```exposePorts 		= true
timeout 			= 60
mesosVersion 		= 0.25
loggingLevel		= INFO
clusterName			= "minimesos-test"

master {

  image = "..."
    
}

agent {

  resources {
	  cpu {
			role  = "logstash"
			value = "0.2"
	   }
	  mem {
			role  = "logstash"
			value = "512M"
	  }
	disk {
	    role = "*"
	    value = "5G"
	}
  }
  
  attributes {
  
	  attribute {
		 key = "rack"
		 value = "rack-01"
	  }
  }  
  
 modules {
   module {
    file = "/path/to/flocker.so"
	config {
	  
    }
   }
   
   module {
   
   }
 } 
	
  imageName 	= "containersol/mesos-agent"
  imageTag		= "0.25"
  loggingLevel	= INFO 

}

zookeeper {
   
}

marathon {

 }

consul {

}
```

**Comment by mwl** [comment]
Might be cynical here, but isn't this a step back towards Docker-compose?

**Comment by frankscholten** [comment]
Docker-compose is too limited since it does allow to create flexible system tests with JUnit. By using our own format we can have both a Java API and a config file.

**Comment by frankscholten** [comment]
Fixed in https://github.com/ContainerSolutions/minimesos/pull/241
