### ISSUE TITLE
Using with cygwin

### ISSUE THREAD

**Issue by josephwinston** [ContainerSolutions/minimesos#189]
You need to enable ```---exposedHostPorts``` on cygwin like you do on OS X.  Something like this would work:

```bash
diff -c /usr/local/bin/minimesos /usr/local/bin/minimesos.~1~
*** /usr/local/bin/minimesos    2016-01-07 14:22:02.358991900 -0600
--- /usr/local/bin/minimesos.~1~        2016-01-07 14:11:51.372491900 -0600
***************
*** 46,53 ****
      pullImage "containersol/mesos-agent" ${MESOS_TAG}
      pullImage "containersol/mesos-master" ${MESOS_TAG}
      echo "Finished pulling images."
!     if [ "$(uname)" = "Darwin" ] || [ "$(uname)" = "CYGWIN_NT-6.1" ]; then
!         echo "Enabling --exposedHostPorts"
          PARAMS="${PARAMS} --exposedHostPorts"
      fi
  fi
--- 46,53 ----
      pullImage "containersol/mesos-agent" ${MESOS_TAG}
      pullImage "containersol/mesos-master" ${MESOS_TAG}
      echo "Finished pulling images."
!     if [ "$(uname)" = "Darwin" ]; then
!         echo "You are running minimesos on OS X, enabling --exposedHostPorts"
          PARAMS="${PARAMS} --exposedHostPorts"
      fi
  fi
```

**Comment by frankscholten** [comment]
@josephwinston Thanks for running minimesos on Cygwin. Could you create a PR for this snippet?

**Comment by josephwinston** [comment]
Sure can.  I was just being lazy.

**Comment by frankscholten** [comment]
@josephwinston Thx!

**Comment by frankscholten** [comment]
Copied from #190 by @josephwinston 

Per https://docs.docker.com/engine/userguide/dockervolumes/, docker-engine only has access to %USERPROFILE% on Windows and $HOME on OS X. One possible way to make MINIMESOS_DIR correct on Windows would be:

 diff -c /usr/local/bin/minimesos /usr/local/bin/minimesos.~1~
*** /usr/local/bin/minimesos    2016-01-07 15:01:41.345735100 -0600
--- /usr/local/bin/minimesos.~1~        2016-01-07 15:09:11.650665200 -0600
***************
*** 53,87 ****
  fi


- ROOT=""
- if [ "$(uname)" = "CYGWIN_NT-6.1" ]; then
-     #
-     # https://docs.docker.com/engine/userguide/dockervolumes/
-     # On Windows, you have access to c:\Users
-     #
-     ROOT=${USERPROFILE}
- else
-     #
-     # https://docs.docker.com/engine/userguide/dockervolumes/
-     # On OS X, you have access to /Users
-     #
-     ROOT=${HOME}
- fi
-
  MINIMESOS_DIR="${ROOT}/.minimesos"
  if [ ! -d ${MINIMESOS_DIR} ]; then
      mkdir -p ${MINIMESOS_DIR}
      echo "Created minimesos directory at ${MINIMESOS_DIR}."
  fi

- if [ "$(uname)" = "CYGWIN_NT-6.1" ]; then
-     #
-     # https://docs.docker.com/engine/userguide/dockervolumes/
-     # On Windows, you need to mount the volume a /c/Users/...
-     #
-     MINIMESOS_DIR=`cygpath --unix "${MINIMESOS_DIR}"|sed s@/cygdrive@@`
- fi
-
  docker run \
         --rm \
         -v "${MINIMESOS_DIR}:/tmp/.minimesos" \
--- 53,64 ----

**Comment by frankscholten** [comment]
Closing for now because we won't support cygwin any time soon.
