### ISSUE TITLE
Error when calling cluster.start more than once

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/minimesos#194]
If people accidentally call cluster.start more than once, you get an obscure docker id error.
```
com.github.dockerjava.api.ConflictException: Conflict. The name "minimesos-zookeeper-3160310531-3957810734" is already in use by container b1a61e37e28e. You have to remove (or rename) that container to be able to reuse that name.
```
It should throw an IllegalStateException to say that the cluster has already started. Or something.

**Comment by sadovnikov** [comment]
@philwinder Did you mean starting the entire cluster for the second time or any particular container?

**Comment by sadovnikov** [comment]
resolved
