### ISSUE TITLE
Minimesos bundles docker client in the image.

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#205]
https://github.com/ContainerSolutions/minimesos-docker/blob/master/base/Dockerfile

Can't use minimesos cause my docker is of different version.
I can upgrade, but, it sure confuses me a lot as to why not bind it with volumes?

**Comment by frankscholten** [comment]
Duplicate of https://github.com/ContainerSolutions/minimesos/issues/324
