### ISSUE TITLE
Save settings of the running cluster to configuration file

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#215]
This is a part of #185 - ability to initialise cluster configuration file based on running container.
Depends on, should be implemented after, #213

**Comment by sadovnikov** [comment]
*Note:*, the current implementation of deserializations does not handle non-default Mesos slave resources. Either Docker env variables need to be parsed or `state.json` of agent (later is preferable)

**Comment by frankscholten** [comment]
I am not sure if this feature is that interesting at the moment.

**Comment by sadovnikov** [comment]
Now clusters are configured by files and there is no way to change the running cluster. Therefore this feature is not needed
