### ISSUE TITLE
remove unnecessary classes

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#217]
from #216, I'm glad to see `MesosSlaveExtended` being deleted. Should you consider getting rid of extensions of `MesosMaster`?

![image](https://cloud.githubusercontent.com/assets/4749332/12913220/b0c1adac-cf1d-11e5-888d-8071ce26c1c5.png)

**Comment by frankscholten** [comment]
Fixed as part of https://github.com/ContainerSolutions/minimesos/pull/241
