### ISSUE TITLE
outdated mesos & marathon versions

### ISSUE THREAD

**Issue by a93ushakov** [ContainerSolutions/minimesos#222]

**Comment by frankscholten** [comment]
You will soon be able to specify Mesos and Marathon versions from the minimesosFile. This feature has already landed in master but is not yet documented.

Have a look at https://github.com/ContainerSolutions/minimesos/blob/master/minimesos/src/test/groovy/com/containersol/minimesos/config/ConfigParserTest.groovy for examples
