### ISSUE TITLE
Restricting the resources declared by slaves

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/minimesos#223]
The agent started by minimesos declares it has the whole memory and cpu of host. It should be possible to restrict the values.

**Comment by frankscholten** [comment]
This is now possible with the minimesosFile. See https://github.com/ContainerSolutions/minimesos/pull/241

**Comment by frankscholten** [comment]
I think this is a matter of taking the resources from the `minimesosFile` and setting them at the Docker level on the Mesos Agent using `docker run -m <mem>`

**Comment by frankscholten** [comment]
Let's investigate how we can prevent a process from exceeding its offered resources.

**Comment by frankscholten** [comment]
Closing for now.
