### ISSUE TITLE
restore and finish implementation consul in minimesos cluster

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#236]
Within #220 and #225 incomplete implementations were removed. 
They need to be restored and finalised after release of 0.6.0

**Comment by alex-glv** [comment]
Is there any progress or plans on how to implement this.
There's the container class still present, can we hook it up under a start flag --consul or something?

**Comment by frankscholten** [comment]
@remmelt is investigating this as part of https://github.com/ContainerSolutions/minimesos/issues/263 by 

Not sure if we need a hook. It can be part of the ClusterArchitecture and possibly replace Docker links.

**Comment by frankscholten** [comment]
What remains to be done is documenting Consul + Registrator. @alex-glv Can you have a look at this?

**Comment by sadovnikov** [comment]
resolved within #349 PR
