### ISSUE TITLE
Maven/Gradle website snippet needs updating

### ISSUE THREAD

**Issue by BenHall** [ContainerSolutions/minimesos#253]
On the website, the name of the Maven groupId for the dependencies is outdated. The website says com.containersolutions  but Jitpack defines it as com.github.ContainerSolutions. 

The Gradle dependencies example also needs updating to 

```
dependencies {
  compile 'com.github.ContainerSolutions:minimesos:0.6.1'
 }
```

Working Maven example - https://github.com/katacoda/minimesos-examples/blob/master/hello-world/pom.xml

**Comment by sadovnikov** [comment]
@alex-glv, could you please correct text on the site?

**Comment by alex-glv** [comment]
Done
