### ISSUE TITLE
Configuration. Cluster name

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#261]
Spin off #185. Providing name of the cluster from configuration file

**Comment by frankscholten** [comment]
Should we use cluster ID for the name? If no clustername is given we can generate one.

**Comment by sadovnikov** [comment]
@frankscholten Are you working on this one? If not, I'll taking it

**Comment by sadovnikov** [comment]
![image](https://cloud.githubusercontent.com/assets/4749332/13562740/e7d67074-e43b-11e5-8ea1-be450ca82ece.png)

**Comment by sadovnikov** [comment]
The code is changed to compose `minimesos-NNNNNN` cluster name

![image](https://cloud.githubusercontent.com/assets/4749332/13562760/1bcb098a-e43c-11e5-8b2f-e26d12da6899.png)
