### ISSUE TITLE
R&D DNS based service discovery in minimesos

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#263]
Find out how to create out of the box service discovery for minimesos.

It should be possible for an executor Docker container to find other services using a DNS service like Consul or Mesos DNS or Avahi.

When deploying Kafka on minimesos the executor could not resolve 'minimesos-zookeeper'. The question is whether the executor will find it when we configure the Mesos Agent to point to Consul or Mesos DNS.

Does the executor inherit the `/etc/resolv.conf` from the Mesos Agent? It runs Docker-outside-of-Docker. Let's create a short experiment to test this out.

**Comment by frankscholten** [comment]
In minimesos the executor does not inherit the ``/etc/resolv.conf`` from the agent.

**Comment by frankscholten** [comment]
Weave also looks promising. See https://katacoda.com/courses/weave/hello-net

**Comment by remmelt** [comment]
It looks like weave could work for minimesos, as long as the various zookeeper internal docker container hostnames can be set to anything.

This is the way the weave dns works, based on those hostnames (or on container names, but then you can only have one instance per node)

As far as I can tell, weave works by replacing the docker socket with a weave specific one, an agent and a proxy on each node
You have to give it the ip of the first node for any second nodes you want to add
You have to download and launch weave, it starts a bunch of containers, then `eval "$(weave env)"`
Then, start zk by `docker run -h zookeeper.weave.local zookeeper` and you can ping it from any attached weave host using `docker run ubuntu ping zookeeper`
This will work from localhost but also from hosts that are running weave as well
It will find the correct container, using MAGIC
Tomorrow I'll look into integrating this with minimesos, to see what I'll run into

**Comment by remmelt** [comment]
http://docs.weave.works/weave/latest_release/weavedns.html

**Comment by frankscholten** [comment]
Had an enlightening chat today with Ilya (@errordeveloper). Thanks for the helping out, Ilya!

In order to support Weave for single node setup we have to:

1. Launch weave proxy and weave router by creating 2 subclasses of `AbstractContainer`. Both processes can be started via the same Docker image at https://hub.docker.com/r/weaveworks/weave. To find out the exact commands run `WEAVE_DEBUG=1 ./weave` and find the Docker commands with the right params and env variables. These have to be started before running the rest of the minimesos cluster.

2. Setup a Weave proxied Docker client which we pass that to the Mesos Agent containers using environment variables. 

3. Configure the naming convention for Weave so that Zookeeper is available at `zookeeper.clustername.weave.local`. By default minimesos container have a name like
`minimesos-role-clusterID-uuid` but let's check if we can add a second Docker name or use `weave dns-add` to register additional names to create the above mentioned convention.

4. Make Weave a collection of singleton containers so when another minimesos cluster is started it reuses the existing Weave containers.

If we have any further questions we can ask Ilya for help.

**Comment by frankscholten** [comment]
Closing for now as we first have to enable basic CNI support.
