### ISSUE TITLE
Docker outside of docker issues

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/minimesos#268]
Here are some issues I have experienced when trying to get the ES framework working in docker mode:
- The executors need access to the sandbox. But the sandbox is in the agent container, not the Host. (System tests worked around this by mounting the sandbox to the host)
- The executors are hardcoded to run in HOST mode so that they get the same IP address as the agent. But this doesnt' work in MM because the docker daemon is not running on the agent, it's running on the host. (this is worked around in the system tests by having iprules that redirect traffic to the docker bridge)
- Executors in host mode were binding to 127.0.0.1 (don't know why)

**Comment by alex-glv** [comment]
@philwinder we are testing docker wrapper that will inject --net and (eventually) --dns parameters.
https://github.com/ContainerSolutions/minimesos/issues/275

This resolves networking issues.
This is a poor man's "pod" at the moment.

**Comment by frankscholten** [comment]
Discussion continues in https://github.com/ContainerSolutions/minimesos/issues/187
