### ISSUE TITLE
minimesos install should retry if cluster inaccessible

### ISSUE THREAD

**Issue by BenHall** [ContainerSolutions/minimesos#272]
`minimesos up` can indicate that the cluster has started. However, when running `minimesos install` it errors as it's unable to connect to Marathon. There should be some built-in retry / timeout to handle the server still starting. 

Advantages:
   - Easier for scripting
   - Easier for Katacoda scenario
   - Error message is confusing as up returned correctly

**Comment by frankscholten** [comment]
When https://github.com/ContainerSolutions/minimesos/pull/279 is merged in this can be fixed by increasing the timeout.

`MesosCluster.start()` the cluster will wait on Master and on Marathon, if configured.
