### ISSUE TITLE
exposePorts config doesn't map to exposedHostPorts

### ISSUE THREAD

**Issue by BenHall** [ContainerSolutions/minimesos#287]
Given this configuration file  https://github.com/katacoda/minimesos-examples/blob/61f9a7a5e03815fa9e47eebae674c3d3fbf0fa1d/elasticsearch-mesos-scheduler/minimesosFile#L3

Running `minimesos up` should automatically set the --exposedHostPorts flag but that doesn't look to be the case.

**Comment by sadovnikov** [comment]
@remmelt, changes in #292 can be interesting for you because you are adding `CommandUp#startConsul`. It should be possible to determine if use has specified parameter value and this value should be taken from configuration file
