### ISSUE TITLE
Remove --ipc=host argument for MesosAgents containers

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#291]
ipc=host allows mesos agent to see hosts /proc tree. This is a work-around for the issue where mesos agent tracks tasks using /proc structure. Therefore, if the /proc structure is not shared, then mesos agent cannot see tasks as processes.

It's enough if agent's tasks and agent process share the same /proc tree (needs verification, though)

This if not removed could be a problem in multi-tenancy mode, since all agents will be able to see hosts procs

**Comment by sadovnikov** [comment]
@alex-glv, could you clarify this one for us when you are in the office?

**Comment by frankscholten** [comment]
@alex-glv Can you clarify this one?

**Comment by alex-glv** [comment]
There's a point of isolation that is removed between the mesos agents and the host.
It's the /proc tree which contains the running processes. Mesos agent needs the /proc tree to be the same as the docker containers that mesos agent starts (this was the case for 0.25, at least, I am not sure how's it progressed). If the mesos-agent cannot see the docker container process under /proc, it loses the track of it. We worked around the issue by passing --ipc=host to the mesos-agent container, which means both mesos-agent and the tasks it start will see the host's /proc tree (with all the processes on the machine). 

The abstraction in this case is breached and it might not work anymore if you try to run minimesos under docker swarm, or on top of any other layer. Hope this makes sense.
