### ISSUE TITLE
references to "slave" in minimesos code

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#294]
Terms `slave` and `slaves` still present in minimesos. 
Is it actually working with newer versions of Mesos?

![image](https://cloud.githubusercontent.com/assets/4749332/13742308/68549876-e9db-11e5-8a60-c7300b234b41.png)

**Comment by frankscholten** [comment]
Closing for now as new Mesos versions still use slave inside the JSON endpoints.
