### ISSUE TITLE
notifications from builds

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#303]
No notifications are being sent by Jenkins build jobs. This should be fixed

**Comment by sadovnikov** [comment]
Example:
![image](https://cloud.githubusercontent.com/assets/4749332/13780660/b04cc7da-eac0-11e5-85cb-27e7d7f04a2d.png)

**Comment by frankscholten** [comment]
Notifications are now sent to #minimesos-internal channel
