### ISSUE TITLE
Installer fails because of Github 404

### ISSUE THREAD

**Issue by BenHall** [ContainerSolutions/minimesos#311]
The installer can sometimes fail because Github returns a 404 error. Would be nice if the install script could automatically retry.

```
curl -sSL https://minimesos.org/install | sh                                             
Failed to pull installer off github.com (http err: 000404), please try again.
```

**Comment by p404** [comment]
I’ve experienced the same issue executing the installer,
I made some tests getting the file from GitHub and I noticed I was getting longer response times than the
expected max-time value from the bash script.

```bash
curl -s -w "%{time_total}\n" -o /dev/null https://raw.githubusercontent.com/ContainerSolutions/minimesos/0.7.1/bin/install-version

4,079

curl -s -w "%{time_total}\n" -o /dev/null https://raw.githubusercontent.com/ContainerSolutions/minimesos/0.7.1/bin/install-version

1,400

```
I've created PR to change the max-time value and added a retry to get along with not-so fast connections.
