### ISSUE TITLE
Mount agent sandbox on host

### ISSUE THREAD

**Issue by philwinder** [ContainerSolutions/minimesos#314]
I'm often using the mesos sandbox (default dir: `/tmp/mesos/slaves/...`) to download config files, download binaries, etc.

When in docker mode, applications start in the context of the host, not the agent. So a command like: `docker run container --config=$MESOS_SANDBOX/config.yml` actually tries to read the config file on the host. I we mounted the sandbox of every agent onto the host, then the other docker containers would be able to use this file.

Each slave uses a sandbox with a unique slave id, so there shouldn't be any clashes. Simply mount `-v /tmp/mesos/slaves:/tmp/mesos/slaves:rw`.

**Comment by alex-glv** [comment]
@philwinder 
A sensible solution would be to create a sandbox directory in minimesos working directory, and a per-agent directory that will be mapped for each agent. What do you think?

**Comment by frankscholten** [comment]
@alex-glv Ah good point. We should have sandbox volumes per cluster. How about adding the `/tmp/mesos/slaves` folder under `${PWD}/.minimesos/`?
