### ISSUE TITLE
Setup pullapprove

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#317]

**Comment by frankscholten** [comment]
@mwl has set this up for https://github.com/ContainerSolutions/mesos-starter

**Comment by frankscholten** [comment]
Added in https://github.com/ContainerSolutions/minimesos/commit/a63f110f410a46e970ef0e6610f85cee947f97e5. Kudos @mwl for setting this up!

**Comment by mwl** [comment]
@frankscholten: Please verify the GH usernames
