### ISSUE TITLE
Slow build times due to building Docker images

### ISSUE THREAD

**Issue by remmelt** [ContainerSolutions/minimesos#318]
Docker images should have a common parent with java already installed. This will speed up new builds significantly. 

Needs a good Jenkins setup to build the common/parent images though.

**Comment by frankscholten** [comment]
How about building via www.travis-ci.com? @mwl has a cool setup with www.travis-ci.com and https://pullapprove.com

**Comment by remmelt** [comment]
The thing is, when do we update? When there are updates to the mesos parent image? To java? Does this automatically trigger downstream builds?

**Comment by frankscholten** [comment]
We now have travis. Anything to do for this issue?

**Comment by sadovnikov** [comment]
Slow build time was due to a bug in the code, which was making unit tests to wait for a minute
