### ISSUE TITLE
Minimesos doesn't cleanup after exceptions during tests

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#331]
It seems that any failed test / or failed containers leaves the cluster running.
 There should be a clean-up routine that is executed when an unfixable cluster state is reached.
(eg can't pull one of the images)

**Comment by alex-glv** [comment]
following @frankscholten I replaced cluster.stop() with cluster.destroy(), now cleanups are mostly done.
HelloWorldContainer does'n get the name prefixed with the cluster id and is not reaped.

**Comment by frankscholten** [comment]
Cool. You have a PR?

**Comment by alex-glv** [comment]
https://github.com/ContainerSolutions/minimesos/pull/340/files
