### ISSUE TITLE
Add user namespaces requirement to minimesos

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#332]
Currently, user namespaces are implemented in docker, but the mappings are not enabled by default.

We'd want this to be minimesos requirement, so any files created within the containers are owned by the user who runs them (or any other user provided to docker for mapping)

This will remove hacks around modifying file ownership on mapped volumes.

**Comment by alex-glv** [comment]
Constant issue we'll be facing is creating files from containers in mapped volumes.
They will be owned by root, which means root on host. 

My suggestion is to address this in the documentation, saying that if you're not using user ns, files created by minimesos will be owned by root.

I think it's imractical to change every created file ownership to 1000

**Comment by frankscholten** [comment]
Closing. This is nice to have but not a priority.
