### ISSUE TITLE
Keep alpine3.3-java8-jre independent from minimesos

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#334]
Currently our `alpine3.3-java8-jre` image contains `ONBUILD` instructions, which makes it `minimesos` specific. If this instruction is taken away and regular `ADD` is added to minimesos image - `alpine3.3-java8-jre` image can be used as base for other images

**Comment by remmelt** [comment]
Doing this, because there are troubles with the build context that I don't want  to un-trouble.

**Comment by remmelt** [comment]
https://github.com/ContainerSolutions/minimesos/pull/329 fixes this
