### ISSUE TITLE
Memory settings not preserved

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/minimesos#341]
I created `minimesosFile` with `minimesos init`, then changed memory specification to 1GB

    agent {
     .....
    mem {
                role = "*"
                value = 1024
            }
     }

but after starting `minimesos up --num-agents=2` only one agent had the specified amount of memory
<img width="773" alt="mesos" src="https://cloud.githubusercontent.com/assets/3329545/14067598/d501bd1e-f467-11e5-8cab-722b9b3e0be9.png">

version: `e0f8d43ea44abe5dd3018d7400c81bdd9109d4b5`

**Comment by alex-glv** [comment]
I think num-agents is a redundant option now. 
To specify resources for agents add the extra ```agent {}``` block in the minimesosFile with the resources you want

**Comment by lguminski** [comment]
Indeed. It looks like an inconsistency.

**Comment by frankscholten** [comment]
Fixed.

Discussion about `num-agents` and resizing continues here: https://github.com/ContainerSolutions/minimesos/issues/363
