### ISSUE TITLE
specify origin and branch on push

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#343]
```
    // push update to repository
    exec {
        workingDir "${project.rootDir}"
        commandLine "git", "push"
    }
```

**Comment by sadovnikov** [comment]
alternative for this:
* adding `minimesos` script as a build artifact, which will replace the `"latest"` with the version, which is being built
* make `Travis CI` to release on tags

**Comment by frankscholten** [comment]
I like the idea of turning the `minimesos` script into a build artifact and using Gradle resource filtering https://dzone.com/articles/resource-filtering-gradle to put the version from `gradle.properties` in there.

**Comment by frankscholten** [comment]
What do you mean by make Travis CI release on tags?

**Comment by sadovnikov** [comment]
This issue was requested by Remelt, he believed and almost convinced me that pushing should be more explicit.
```
// push update to repository
exec {
    workingDir "${project.rootDir}"
    commandLine "git", "push", "origin"
}
```
I'm not sure anymore. Maybe we should close this

**Comment by frankscholten** [comment]
Let's close this. I will create a new issue for turning `minimesos` into a build artifact.
