### ISSUE TITLE
Reading old minimesos configs

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/minimesos#350]
The format of minimesos config file changes. If somebody stores it in her project tree, minimesos should be able to deal with it. Either 
* by being able to read all old versions
* or by automatically upgrading the file to latest version (and raising an error if this is not possible)

**Comment by frankscholten** [comment]
Minimesos is too changing too rapidly at the moment to support backwards compatiblity with older `minimesosFile`s
