### ISSUE TITLE
Improve resizing (proposal)

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/minimesos#363]
It would be nice if I could quickly scale up a cluster. Currently (0.8.0) for that you need to 

1. stop running cluster `minimesos destroy`
1. modify configuration file (typically copy & paste)
1. start a new cluster `minimesos up`

This is not very handy, if every time you need to update a config file. Instead I would to accomplish it with just two commands:

1. stop running cluster `minimesos destroy`
1. start a new cluster `minimesos up --num-agents=X`

The first scenario makes sense, if you want to have each agents to have different settings. I think it is a very rare scenario and you can safely drop it.

**Comment by sadovnikov** [comment]
@frankscholten , @lguminski Would you agree with `minimesos up --num-agents=X` working only when configuration file contains one agent definition? Otherwise use of `--num-agents` is invalid.

**Comment by frankscholten** [comment]
I like the idea of resizing but I don't see how it would fit in the current design.

The current design implies that the cluster is immutable. You define it once in a `minimesosFile`, create it, use it and then destroy it. Resizing it makes the cluster mutable. 

We could however support the ability to add an agent by creating a separate cluster that connects to the previous one. Let's say you start a cluster. Then in another directory you create another cluster with an agent that points to the Master or Zookeeper of the previous cluster.

**Comment by frankscholten** [comment]
Closing for now. Other issues like removing tech debt and adding API are more important.
