### ISSUE TITLE
Running on EC2

### ISSUE THREAD

**Issue by jedi132000** [ContainerSolutions/minimesos#367]
Tried running on an EC2 instance, the framework starts on a private IP in EC2, which isn't available via the internet, Any walk arounds?

**Comment by frankscholten** [comment]
This should work when the cluster's containers run in `host` mode. This is not yet implemented yet. See https://github.com/ContainerSolutions/minimesos/pull/316

**Comment by frankscholten** [comment]
@jedi132000 Have a look at @philwinder's blog at Container Solutions on how to run minimesos on AWS http://container-solutions.com/minimesos-on-aws

**Comment by jedi132000** [comment]
Will do thank you.
