### ISSUE TITLE
install on minimesos.org

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#368]
there is a problem on minimesos.org:   https://minimesos.org/install file does not match https://github.com/ContainerSolutions/minimesos/blob/0.8.0/bin/install 

Therefore
![image](https://cloud.githubusercontent.com/assets/4749332/14199499/3adc969c-f7e5-11e5-9413-91b843dff1be.png)

**Comment by alex-glv** [comment]
Install file is statically stored under minimesos.org repo
https://github.com/ContainerSolutions/minimesos.org/blob/master/themes/minimesos/static/install

Perhaps, that should be automatically pulled off github

**Comment by alex-glv** [comment]
I have made the minimesos.org/install a wrapper, that pulls the latest installer off the minimesos repo.
https://github.com/ContainerSolutions/minimesos.org/blob/master/themes/minimesos/static/install
