### ISSUE TITLE
Find a better way to figure out if docker is running on a VM for ports expose and routing 

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#378]
Currently, --exposHostPorts is forcefully turned on when running on OSX.
Also, the route add documentation is only working on OSX, but not on linux when running with docker-machine.

Fix the doc, add the linux 'route add' command

```
sudo route add -net 172.17.0.0 netmask 255.255.0.0 gw ${docker-machine ip default}
```

**Comment by frankscholten** [comment]
@alex-glv Can you have a look at this. We can then remove the `--exposeHostPorts` flag in https://github.com/ContainerSolutions/minimesos/issues/390

**Comment by frankscholten** [comment]
@remmelt Can you look at this one?

**Comment by frankscholten** [comment]
This command works for Mac OSX users. It does not work for Linux users as they typically already have a `docker0` interface on a `172.17.0.0` subnet.
