### ISSUE TITLE
Publish minimesos in Maven Central

### ISSUE THREAD

**Issue by mwl** [ContainerSolutions/minimesos#380]
This is easy achievable through Bintray and JCenter.

Here the things I see that we're missing before we can make it into JCenter
- [x] Produce `-javadoc.jar` artefact
- [x] Fix a rather long list of incomplete javadoc sections
- [x] Produce `-sources.jar`artefact
- [ ] `<developers>` section of pom.xml might need some more information

Optional:
- [ ] Integrate publishing to Bintray into Travis build
- [ ] Migrate installation scripts to use JCenter/Maven Central
- [x] ~~`groupId` with "com.github" is not preferable~~

**Comment by mwl** [comment]
So far I've managed to publish the `.jar` and `.pom` at https://bintray.com/containersolutions/maven/minimesos/

Though `-javadoc.jar` and `-source.jar` is still missing.

**Comment by frankscholten** [comment]
@mwl Is this something you like to contribute?

**Comment by mwl** [comment]
@frankscholten Definitely. I'll have a look again and create a list of action points.

**Comment by frankscholten** [comment]
Closing for now.
