### ISSUE TITLE
Improve error message when no cluster is running

### ISSUE THREAD

**Issue by schoefmann** [ContainerSolutions/minimesos#416]
Running e.g. `$ minimesos info` in a different directory where `$ minimesos up` was run, the error message `Minimesos cluster is not running` is confusing for users who are not aware that you can run multiple clusters in parallel.

Maybe have `No Minimesos cluster is running in the current directory` instead

**Comment by sadovnikov** [comment]
@schoefmann Would these messages work?

Cluster is not started from this directory
```
vikmac:mini-mesos vik$ bin/minimesos info
Cluster ID is not found in /Users/vik/projects/cs/devbox/sources/mini-mesos/.minimesos/minimesos.cluster
```

Cluster was stared, but there are no matching containers found
```
vikmac:mini-mesos vik$ bin/minimesos info
Minimesos cluster 902141895 is not running. /Users/vik/projects/cs/devbox/sources/mini-mesos/.minimesos/minimesos.cluster is removed
```
