### ISSUE TITLE
Weave scope doesn't start

### ISSUE THREAD

**Issue by loacker** [ContainerSolutions/minimesos#432]
I'm testing minimesos on a Vagrant virtual machine using the official ubuntu image "ubuntu/trusty64".

I run the following step:

minimesos init
minimesos up

The Weave Scope docker image is never downloaded, the task is accepted but continue to fail and there are no logs.
I'm running the following version of software:

OS: "Ubuntu 14.04.4 LTS"

minimesos version: 0.9.0

docker version:
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by frankscholten** [comment]
You probably have a Docker versinon that is too old. Can you show me the url of your Vagrantfile?

**Comment by loacker** [comment]
You can find the Vagrantfile I used on the following gist, Note I'm using KVM (with libvirt) instead of VirtualBox, I tested it using the ubuntu image provided by canonical from atlas "ubuntu/trusty64".

https://gist.github.com/loacker/1ad075bbec01567b42a82c6466fce66a

**Comment by frankscholten** [comment]
@loacker That VM does not have Docker installed. Which Docker version did you install?

**Comment by loacker** [comment]
Hello @frankscholten

I just installed it using apt:

apt-get install docker.io

**Comment by amouat** [comment]
You're using an old Ubuntu packaged version.

Try installing with `curl -sSL https://get.docker.com/ | sh` or follow the instructions on the Docker website to use their apt repo. You can check your Docker version with `docker version`.

**Comment by frankscholten** [comment]
Thanks @amouat
