### ISSUE TITLE
mesos 0.28

### ISSUE THREAD

**Issue by kovrus** [ContainerSolutions/minimesos#436]
Hi, thanks for the awesome mesos testing framework. Do you plan to support Mesos 0.28 anytime soon?

**Comment by frankscholten** [comment]
Sure, I have opened an issue at https://github.com/ContainerSolutions/minimesos-docker/issues/11

**Comment by frankscholten** [comment]
Fixed in https://github.com/ContainerSolutions/minimesos/pull/471 and https://github.com/ContainerSolutions/minimesos-docker/pull/12
