### ISSUE TITLE
DiscoverySystemTest fails with mesosVersion = "0.27"

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/minimesos#446]
The cluster starts up and spawns a bunch of task containers but the test stiff fails to get the hello world responses from them.

Reproduce:
* Change mesosVersion to 0.27 in minimesosFile-discoverySystemTest
* Run DiscoverySystemTest

**Comment by frankscholten** [comment]
The reason this test fails is that the test-framework module uses Mesos 0.25 so it cannot find the correct libmesos version. When I temporarily change the framework images to 0.27 and rebuild the test passes,
