### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/minimesos#452]
Create a RESTful API module for Minimesos that will be the universal controller for all actions and verifications done on the cluster. This will make Minimesos usable from any language with only a thin client library required.

The API would be a long-lived container started with `minimesos up` replacing the current short-lived minimesos container. In the new architecture both the Java API and CLI would only be clients to this API which would encapsulate all the core logic that is directly called now.

![restapi](https://cloud.githubusercontent.com/assets/10675791/15504824/187198c2-21c1-11e6-8da9-2a323806e18d.png)
- [x] Extract CLI code into CLI module https://github.com/ContainerSolutions/minimesos/issues/453
- [ ] Create API server in minimesos module https://github.com/ContainerSolutions/minimesos/issues/456
- [ ] Add Java client that calls API
- [ ] Change cli so it calls API
- [ ] Modify Test framework to use Java client
- [ ] Remove code that is no longer needed (e.g. cluster configuration restore logic in `MesosClusterContainersFactory`)

**Comment by frankscholten** [comment]
Closing for now.
