### ISSUE TITLE
Better information for user after `minimesos up` on Mac

### ISSUE THREAD

**Issue by adam-sandor** [ContainerSolutions/minimesos#459]
Mac users are seeing incomplete or incorrect information when running `minimesos up`:
- If they are using docker-machine we should notify them that they need to alter the routing table: `sudo route delete 172.17.0.0/16; sudo route -n add 172.17.0.0/16 $(docker-machine ip ${DOCKER_MACHINE_NAME})`. It would be best to print this command on the outout so the user doesn't have to search for it in the docs.
- If running with --mapHostPorts then we should print also the IP and ports that are available. IP is needed because on mac it will be the docker-machine IP - in case docker4mac is not used.
- Notify the user that docker4mac is not supported until we figure out a way to access the containers (maybe --mapHostPorts helps, I will verify this)

**Comment by frankscholten** [comment]
This is fixed by https://github.com/ContainerSolutions/minimesos/pull/511.

A message is printed which says to use localhost for when running on Docker on Mac.
