### ISSUE TITLE
Error building minimesos for docker-machine in mac

### ISSUE THREAD

**Issue by mcortinas** [ContainerSolutions/minimesos#460]
Hi,

 I'm trying to run minimesos and after read the doc [http://minimesos.readthedocs.io/en/latest/#installing](http://minimesos.readthedocs.io/en/latest/#installing) I tried build and run on Mac with docker-machine

Environment:
- OSX Capitan with 10.11.5 (15F34)
- docker-machine version 0.7.0, build a650a40
- Docker version 1.11.2, build b9f10c9
- VirtualBox Version 5.0.20 r106931

[minimesos-build-reports.tar.gz](https://github.com/ContainerSolutions/minimesos/files/299774/minimesos-build-reports.tar.gz)

My main error is the Image mesos-master:0.27.1-2.0.226.ubuntu1404] not found after launch command "./gradlew install", I paste the error log.

> 06:38:15.161 [DEBUG] [TestEventLogger] com.containersol.minimesos.RestoreConfigurationFromRunningClusterTest STANDARD_OUT
06:38:15.161 [DEBUG] [TestEventLogger]     06:38:15.160 [Test worker] DEBUG c.c.minimesos.cluster.MesosCluster: Cluster 2986485380 - start
06:38:15.200 [DEBUG] [TestEventLogger]     06:38:15.200 [Test worker] DEBUG c.c.m.container.AbstractContainer: Creating container [minimesos-zookeeper-2986485380-2123273593]
06:38:16.399 [DEBUG] [TestEventLogger]     06:38:16.399 [Test worker] DEBUG c.c.m.container.AbstractContainer: Container de1c77334267750f152d54c80aaf762e96b2831eb223fe0e205bf0040a405137 is up and running
06:38:16.448 [DEBUG] [TestEventLogger]     06:38:16.448 [Test worker] DEBUG c.c.m.container.AbstractContainer: Image [containersol/mesos-master:0.27.1-2.0.226.ubuntu1404] not found. Pulling...
06:43:16.582 [QUIET] [system.out] 06:43:16.573 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor] Executing test class com.containersol.minimesos.RunTaskTest
06:43:16.588 [DEBUG] [TestEventLogger]
06:43:16.592 [DEBUG] [TestEventLogger] com.containersol.minimesos.RestoreConfigurationFromRunningClusterTest > classMethod STARTED
06:43:17.284 [DEBUG] [TestEventLogger]
06:43:17.284 [DEBUG] [TestEventLogger] com.containersol.minimesos.RestoreConfigurationFromRunningClusterTest > classMethod FAILED

Furthermore , I attached the build report zipped

**Comment by adam-sandor** [comment]
Hi @mcortinas! Thanks for taking the time to submit the report. My guess is that the problem is a slow download of the docker image. The download is happening inside a timed block which is supposed to guard the startup of the container and doesn't calculate with a possible long download of the image.

Please try to do a `docker pull containersol/mesos-master:0.27.1-2.0.226.ubuntu1404` to verify if that fixes the problem. We can update the code later to make sure this doesn't happen.

**Comment by mcortinas** [comment]
you're right! i downloaded the image previously and it fix it the build, thank you @adam-sandor

**Comment by adam-sandor** [comment]
glad it worked! I created #461 to fix this properly.
