### ISSUE TITLE
 docker.io/containersol/minimesos-cli doesn't exist

### ISSUE THREAD

**Issue by pjlegato** [ContainerSolutions/minimesos#479]
Running "minimesos init" with the version from master branch (which is required to run with the Docker 1.12 used in the new Mac Docker app) results in:

```
Unable to find image 'containersol/minimesos-cli:latest' locally
Pulling repository docker.io/containersol/minimesos-cli
docker: Error: image containersol/minimesos-cli:latest not found.
See 'docker run --help'.
```

It appears to be true; there is no minimesos-cli available in https://hub.docker.com/u/containersol/ at the moment.

Two changes seem to fix this:

* Changing line 57 of the `minimesos` script to run just        `containersol/minimesos:${MINIMESOS_TAG} \` (instead of `minimesos-cli`), 
* and changing line 61 to refer to `minimesos.jar` rather than `minimesos-cli.jar` 

This makes the script look like the version in the 0.9.0 branch.

**Comment by frankscholten** [comment]
@pjlegato Thanks for opening this issue. We are currently working on 0.9.1 where we will fix this and other issues.

**Comment by frankscholten** [comment]
See https://hub.docker.com/r/containersol/minimesos-cli/
