### ISSUE TITLE
Unable to run  minimesos on OSX with docker 1.12

### ISSUE THREAD

**Issue by quamilek** [ContainerSolutions/minimesos#488]
I have try to run minimesos on OSX 10.11.4,  I got following errors:

```
$ minimesos up
docker: Error response from daemon: Mounts denied: 
The path /usr/local/bin/docker
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.

```

Docker version:
```
$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64
```

**Comment by frankscholten** [comment]
Hi @quamilek, Docker for Mac it not supported yet. See this https://github.com/ContainerSolutions/minimesos/issues/431

**Comment by jetztgradnet** [comment]
I also have this issue. The workaround using socat as described in #431 helps to get around the problem with accessing the port, but this problem still occurs.

**Comment by eugene-goldberg** [comment]
Same issue:  docker: Error response from daemon: Mounts denied

**Comment by miroswan** [comment]
Removing the -v flag from the minimesos bash script that mounts the docker binary will allow you to execute minimesos. Not sure about how it will function though...

**Comment by eugene-goldberg** [comment]
thanks!
