### ISSUE TITLE
Use official OpenJDK image as base

### ISSUE THREAD

**Issue by charlvanniekerk** [ContainerSolutions/minimesos#499]
`containersol/alpine3.3-java8-jre:v1` is being used as base image in `cli/Dockerfile` in `master` and `alpine:3.3` in the `mesos-docker-images` feature branch.

Perhaps it is better to use the official `openjdk:8-jre-alpine` image instead?

**Comment by adam-sandor** [comment]
I agree that would be better. I'll have to check if there is any reason we use our own image.

**Comment by frankscholten** [comment]
Thx for reporting @charlvanniekerk!
