### ISSUE TITLE
minimesos fails to start Fedora 25

### ISSUE THREAD

**Issue by mcortinas** [ContainerSolutions/minimesos#512]
I try to use minimesos in my laptop without lucky....
I pasted my traces...

[minimesosErrorFedora25.txt](https://github.com/ContainerSolutions/minimesos/files/567486/minimesosErrorFedora25.txt)

**Comment by frankscholten** [comment]
Hi @mcortinas.

See the error message. You first have to create a `minimesosFile` with `minimesos init`.

```
Failed to run command 'up'. No minimesosFile found in current directory. Please generate one with 'minimesos init'
```
