### ISSUE TITLE
Question regarding registrator and consul

### ISSUE THREAD

**Issue by cotigao** [ContainerSolutions/minimesos#519]
What makes the registrator skip the mesos-agent container for consul entry? 

I get the following output (curl 172.17.0.7:8500/v1/catalog/services)
{"consul":[],"marathon":[],"mesos-master":[], "zookeeper-2181":[],"zookeeper-2888":[],"zookeeper-3888":[]}

Also, there isn't any entry for weaveworks/scope container (mesos task) that is running? Isn't that app listening on any port?

**Comment by frankscholten** [comment]
Could be that it is because scope runs on the host network.

**Comment by cotigao** [comment]
ok. so basically the container  needs to be on the same network as the registrator?

**Comment by frankscholten** [comment]
I had a look at this and I upgraded Consul and changed the port number to 8600. See https://github.com/ContainerSolutions/minimesos/commit/78b2b888ac5221563c552a77bf435a160850ffd1

I don't know why the agent is not registered as a service though.
