### ISSUE TITLE
Jitpack - wrong artifact is published 

### ISSUE THREAD

**Issue by przemek1990** [ContainerSolutions/minimesos#521]
https://minimesos.org/ tab Gradle:
```
dependencies {
  compile 'com.github.ContainerSolutions:minimesos:0.10.2'
 }
```
Jitpack https://jitpack.io/#containersolutions/minimesos/0.10.2
```
dependencies {
   compile 'com.github.containersolutions.minimesos:mesos-hello-world-executor:0.10.2'
}
```

**Comment by przemek1990** [comment]
https://jitpack.io/com/github/containersolutions/minimesos/0.10.2/build.log
BUILD SUCCESSFUL

```
Total time: 8.503 secs
Gradle exit code 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Found artifact: com.containersol.minimesos:minimesos-cli:0.10.2
Found artifact: com.containersol.minimesos:minimesos:0.10.2
Found artifact: com.containersol.minimesos:test-framework-docker:0.10.2
Found artifact: com.containersol.minimesos:mesos-hello-world-executor:0.10.2
Found artifact: com.containersol.minimesos:mesos-hello-world-scheduler:0.10.2
Found artifact: com.containersol.minimesos:system-test:0.10.2
```

`com.containersol.minimesos:minimesos:0.10.2` should be available from jitpack instead of Found `com.containersol.minimesos:mesos-hello-world-executor:0.10.2`

**Comment by frankscholten** [comment]
@przemek1990 Which artifact cannot be downloaded? The minimesos jar is available here: https://jitpack.io/com/github/containersolutions/minimesos/minimesos/0.10.2/minimesos-0.10.2.jar

**Comment by przemek1990** [comment]
@frankscholten I mean artifact  `com.github.ContainerSolutions:minimesos:0.10.2`

I'm getting error when trying to download from sbt:

Error:Error while importing SBT project:<br/>...<br/><pre>[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.containersol.minimesos:scheduler:0.10.2
[warn] 		  +- com.github.ContainerSolutions.minimesos:system-test:0.10.2
[warn] 		  +- com.github.ContainerSolutions:minimesos:0.10.2 (/path/batch/build.sbt#L1-9)
[warn] 		  +- com.my_project:1.0
[warn] 		com.containersol.minimesos:executor:0.10.2
[warn] 		  +- com.github.ContainerSolutions.minimesos:system-test:0.10.2
[warn] 		  +- com.github.ContainerSolutions:minimesos:0.10.2 (/path/build.sbt#L1-9)
[warn] 		  +- com.my_project:1.0
[error] (batch/*:update) sbt.ResolveException: unresolved dependency: com.containersol.minimesos#scheduler;0.10.2: not found
[error] unresolved dependency: com.containersol.minimesos#executor;0.10.2: not found
[error] (batch/*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: com.containersol.minimesos#scheduler;0.10.2: not found
[error] unresolved dependency: com.containersol.minimesos#executor;0.10.2: not found
[error] (spark-analytics/*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: com.containersol.minimesos#scheduler;0.10.2: not found
[error] unresolved dependency: com.containersol.minimesos#executor;0.10.2: not found
[error] Total time: 24 s, completed Dec 21, 2016 11:15:57 AM

**Comment by frankscholten** [comment]
The example hello-world framework has been removed a while back because it took a lot of time to build and did not add much value.
