### ISSUE TITLE
Installer Broken

### ISSUE THREAD

**Issue by kensipe** [ContainerSolutions/minimesos#537]
Using a new machine... installing Mini-Mesos and running into a failure. 

error:
```
 curl -sSL https://minimesos.org/install | sh
Failed to pull installer off github.com (http err: 000404), please try again.
```

Debugging...   https://api.github.com/repos/containersolutions/minimesos/releases/latest  exists and provides urls for tarball and url which are functional.
https://github.com/ContainerSolutions/minimesos/releases/tag/0.13.0 is fine... 

However `https://minimesos.org/install` runs https://raw.githubusercontent.com/ContainerSolutions/minimesos/master/bin/install

https://github.com/ContainerSolutions/minimesos/blob/master/bin/install#L26
returns `0.13.0`
which results in https://github.com/ContainerSolutions/minimesos/blob/master/bin/install#L34
==  https://raw.githubusercontent.com/ContainerSolutions/minimesos/0.13.0
which is invalid.

**Comment by kensipe** [comment]
actually... the script does do a call not to https://raw.githubusercontent.com/ContainerSolutions/minimesos/0.13.0/bin/install-version which should be good :( .

**Comment by kensipe** [comment]
well odd..  now it works... closing.   
(manually stepping through the script to debug eventually it worked... started at the beginning and it works... perhaps it was odd timing of github outage...  IDK)

**Comment by frankscholten** [comment]
Seems to be a network outage indeed. See https://status.github.com/messages
