### ISSUE TITLE
Support auth

### ISSUE THREAD

**Issue by jhftrifork** [ContainerSolutions/minimesos#71]
Motivated by https://github.com/mesos/elasticsearch/issues/304

**Comment by jhftrifork** [comment]
To quote [the documentation](http://mesos.apache.org/documentation/latest/authorization/):

> Mesos 0.20.0 adds support for framework authorization. Authorization allows
> 
> 1. Frameworks to (re-)register with authorized roles.
> 2. Frameworks to launch tasks/executors as authorized users.
> 3. Authorized principals to shutdown framework(s) through “/shutdown” HTTP endpoint.

I assume that it's number 2 we're interested in right now.

**Comment by jhftrifork** [comment]
We already support number 1, but in a gross way with the environment variable `MESOS_ROLES`. These environment variables are passed to Docker when creating the Mesos local container. The `MESOS_ROLES` environment variable is picked up by the Mesos master. According to [the Mesos configuration documentation](http://mesos.apache.org/documentation/latest/configuration/), all command-line options can also be passed as environment variables. So the `--acls` option can also be passed as a `MESOS_ACLS` environment variable. This means that technically mini-mesos should already support configuration of auth via the `extraEnvironmentVariables` property of `MesosClusterConfig`. The only problem is that it's ugly, and mini-mesos could/should provide a proper API for this.

**Comment by frankscholten** [comment]
Fixed in https://github.com/mesos/elasticsearch/issues/304
