### ISSUE TITLE
Main exits with code 130

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#73]
```
Started zookeeper on 172.17.0.19
Started mesos master on http://172.17.0.20:5050
Starting Mesos Local
Started Mesos slave at 172.17.0.21

Process finished with exit code 130
```

**Comment by frankscholten** [comment]
When I run Main in IntelliJ and kill it the procses exits with 130. Not clear why.

**Comment by sadovnikov** [comment]
things changed after moving Java process to container. Now, when you run Main from IntelliJ, you get silly error due to absence of `minimesos.dir` system property

**Comment by sadovnikov** [comment]
@frankscholten do you remember what exactly is this issue about? Which process do you kill? When?

**Comment by frankscholten** [comment]
I start Main from IntelliJ and if I then hit the stop button it exits with 130. Check if this still happens.

**Comment by sadovnikov** [comment]
No, this does not happen (anymore)
