### ISSUE TITLE
Separate JUnit code from core

### ISSUE THREAD

**Issue by frankscholten** [ContainerSolutions/minimesos#8]
Extract a core module that does not have a dependency on JUnit

**Comment by frankscholten** [comment]
Would be cool to have example tests that work with Spock

**Comment by sadovnikov** [comment]
Seems to be closed premature.

**Comment by sadovnikov** [comment]
There are a couple of thing remain after introduction of `MesosClusterTestRule`:
* the `MesosClusterTestRule` should move to a separated module;
* `minimesos` should lose compilation dependency on junit

**Comment by frankscholten** [comment]
Fixed after recent refactoring.
